services:
  
  ekh-postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - ekh-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ekh_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ekh_postgres_data:

networks:
  ekh-network:
    driver: bridge